"""Public technographics — stack fingerprints from HTML markers and copy."""

from __future__ import annotations

import re
from collections import Counter
from typing import Any

# (category, product, patterns) — HTML/script markers + plain-language mentions
STACK: list[tuple[str, str, re.Pattern[str]]] = [
    ("cms", "wordpress", re.compile(r"wp-content|wordpress\.com|generated by wordpress", re.I)),
    ("cms", "webflow", re.compile(r"webflow\.io|data-wf-|webflow\.com", re.I)),
    ("cms", "wix", re.compile(r"wix\.com|static\.wixstatic|wixpress", re.I)),
    ("cms", "squarespace", re.compile(r"squarespace\.com|sqsp\.net|static\.squarespace", re.I)),
    ("cms", "shopify", re.compile(r"cdn\.shopify|myshopify\.com|shopify\.com", re.I)),
    ("cms", "ghost", re.compile(r"ghost\.io|ghost\.org", re.I)),
    ("analytics", "google_analytics", re.compile(r"google-analytics\.com|googletagmanager\.com|gtag\(|ga\('create'", re.I)),
    ("analytics", "mixpanel", re.compile(r"mixpanel\.com|cdn\.mxpnl", re.I)),
    ("analytics", "segment", re.compile(r"cdn\.segment\.com|analytics\.js", re.I)),
    ("analytics", "hotjar", re.compile(r"static\.hotjar\.com|hotjar\.com", re.I)),
    ("analytics", "plausible", re.compile(r"plausible\.io", re.I)),
    ("crm", "hubspot", re.compile(r"js\.hs-scripts\.com|hubspot\.com|hs-analytics", re.I)),
    ("crm", "salesforce", re.compile(r"salesforce\.com|force\.com|pardot", re.I)),
    ("crm", "intercom", re.compile(r"widget\.intercom\.io|intercomcdn|intercom\.com", re.I)),
    ("crm", "zendesk", re.compile(r"static\.zdassets|zendesk\.com", re.I)),
    ("email", "mailchimp", re.compile(r"list-manage\.com|mailchimp\.com|chimpstatic", re.I)),
    ("email", "klaviyo", re.compile(r"static\.klaviyo|klaviyo\.com", re.I)),
    ("email", "convertkit", re.compile(r"convertkit\.com", re.I)),
    ("chat", "drift", re.compile(r"js\.driftt\.com|drift\.com", re.I)),
    ("chat", "crisp", re.compile(r"client\.crisp\.chat", re.I)),
    ("chat", "tidio", re.compile(r"code\.tidio\.co", re.I)),
    ("chat", "tawk", re.compile(r"embed\.tawk\.to", re.I)),
    ("payments", "stripe", re.compile(r"js\.stripe\.com|stripe\.com", re.I)),
    ("payments", "paypal", re.compile(r"paypal\.com|paypalobjects", re.I)),
    ("payments", "square", re.compile(r"squareup\.com|squarecdn", re.I)),
    ("hosting", "cloudflare", re.compile(r"cloudflare|cdnjs\.cloudflare", re.I)),
    ("hosting", "vercel", re.compile(r"vercel\.app|_vercel|vercel\.com", re.I)),
    ("hosting", "netlify", re.compile(r"netlify\.app|netlify\.com", re.I)),
    ("hosting", "aws", re.compile(r"amazonaws\.com|cloudfront\.net", re.I)),
    ("hosting", "google_cloud", re.compile(r"googleapis\.com|gstatic\.com", re.I)),
    ("ads", "meta_pixel", re.compile(r"connect\.facebook\.net|fbevents\.js|fbq\(", re.I)),
    ("ads", "google_ads", re.compile(r"googleadservices|doubleclick\.net|gtag/js\?id=AW-", re.I)),
    ("ads", "linkedin_insight", re.compile(r"snap\.licdn\.com|linkedin\.com/px", re.I)),
    ("scheduling", "calendly", re.compile(r"assets\.calendly\.com|calendly\.com", re.I)),
    ("scheduling", "cal_com", re.compile(r"cal\.com", re.I)),
    ("support", "gorgias", re.compile(r"gorgias\.chat|gorgias\.com", re.I)),
    ("support", "freshdesk", re.compile(r"freshdesk\.com|freshworks", re.I)),
]

MENTION_STACK: list[tuple[str, str, re.Pattern[str]]] = [
    ("crm", "hubspot", re.compile(r"\bhubspot\b", re.I)),
    ("crm", "salesforce", re.compile(r"\bsalesforce\b", re.I)),
    ("email", "mailchimp", re.compile(r"\bmailchimp\b", re.I)),
    ("email", "klaviyo", re.compile(r"\bklaviyo\b", re.I)),
    ("outreach", "instantly", re.compile(r"\binstantly\.ai\b|\binstantly\b", re.I)),
    ("outreach", "apollo", re.compile(r"\bapollo\.io\b|\bapollo\b", re.I)),
    ("outreach", "lemlist", re.compile(r"\blemlist\b", re.I)),
    ("ads", "google_ads", re.compile(r"\bgoogle ads\b|\badwords\b", re.I)),
    ("cms", "shopify", re.compile(r"\bshopify\b", re.I)),
    ("cms", "wordpress", re.compile(r"\bwordpress\b|\bwp\b", re.I)),
    ("analytics", "ga4", re.compile(r"\bga4\b|\bgoogle analytics\b", re.I)),
]


def fingerprint_html(html: str) -> list[dict[str, str]]:
    """Return [{category, product, evidence}] from raw HTML."""
    if not html:
        return []
    sample = html[:180_000]
    found: list[dict[str, str]] = []
    seen: set[str] = set()
    for category, product, pat in STACK:
        m = pat.search(sample)
        if not m:
            continue
        key = f"{category}:{product}"
        if key in seen:
            continue
        seen.add(key)
        frag = m.group(0)[:80]
        found.append({"category": category, "product": product, "evidence": frag, "source": "html"})
    return found


def extract_technographics(lead: dict[str, Any]) -> dict[str, Any]:
    hits: list[dict[str, str]] = []
    seen: set[str] = set()

    for item in lead.get("tech_fingerprint") or []:
        if isinstance(item, dict) and item.get("product"):
            key = f"{item.get('category')}:{item['product']}"
            if key not in seen:
                seen.add(key)
                hits.append({
                    "category": str(item.get("category") or "unknown"),
                    "product": str(item["product"]),
                    "evidence": str(item.get("evidence") or "")[:80],
                    "source": str(item.get("source") or "stored"),
                })

    html_blob = str(lead.get("html_snippet") or "")
    for item in fingerprint_html(html_blob):
        key = f"{item['category']}:{item['product']}"
        if key not in seen:
            seen.add(key)
            hits.append(item)

    text = _text(lead)
    for category, product, pat in MENTION_STACK:
        if not pat.search(text):
            continue
        key = f"{category}:{product}"
        if key in seen:
            continue
        seen.add(key)
        hits.append({"category": category, "product": product, "evidence": "mentioned", "source": "copy"})

    by_cat: dict[str, list[str]] = {}
    for h in hits:
        by_cat.setdefault(h["category"], []).append(h["product"])

    maturity = _maturity(by_cat)
    return {
        "products": hits,
        "by_category": {k: sorted(set(v)) for k, v in by_cat.items()},
        "stack_size": len(hits),
        "maturity": maturity,
        "has_crm": "crm" in by_cat,
        "has_analytics": "analytics" in by_cat,
        "has_ads": "ads" in by_cat,
        "cms": (by_cat.get("cms") or [None])[0],
        "confidence": min(90, 20 + 12 * len(hits) + (15 if html_blob or lead.get("tech_fingerprint") else 0)),
    }


def technographic_landscape(leads: list[dict[str, Any]]) -> dict[str, Any]:
    packets = [extract_technographics(l) for l in leads]
    products: Counter[str] = Counter()
    categories: Counter[str] = Counter()
    for p in packets:
        for hit in p["products"]:
            products[hit["product"]] += 1
            categories[hit["category"]] += 1
    with_stack = sum(1 for p in packets if p["stack_size"] > 0)
    return {
        "analysed": len(packets),
        "with_stack": with_stack,
        "coverage": round(100 * with_stack / max(1, len(packets)), 1),
        "top_products": [{"name": k, "count": v} for k, v in products.most_common(12)],
        "categories": [{"name": k, "count": v} for k, v in categories.most_common()],
        "crm_penetration": round(100 * sum(1 for p in packets if p["has_crm"]) / max(1, len(packets)), 1),
        "ads_penetration": round(100 * sum(1 for p in packets if p["has_ads"]) / max(1, len(packets)), 1),
    }


def stack_gap(offer: str, tech: dict[str, Any]) -> dict[str, Any]:
    """Where the offer can wedge relative to detected stack."""
    products = {h["product"] for h in tech.get("products") or []}
    offer_l = (offer or "").lower()
    conflicts = []
    complements = []

    rivals = {
        "instantly": "outreach", "lemlist": "outreach", "apollo": "outreach",
        "hubspot": "crm", "salesforce": "crm", "mailchimp": "email",
    }
    for product, cat in rivals.items():
        if product in products:
            if any(w in offer_l for w in (product, cat, "email", "crm", "outreach", "appointment", "setter")):
                conflicts.append(product)
            else:
                complements.append(product)

    missing = []
    if not tech.get("has_crm") and re.search(r"\b(crm|pipeline|lead)\b", offer_l):
        missing.append("crm")
    if not tech.get("has_analytics") and re.search(r"\b(analytics|tracking|attribution)\b", offer_l):
        missing.append("analytics")
    if not tech.get("has_ads") and re.search(r"\b(ads|paid|media)\b", offer_l):
        missing.append("ads")

    wedge = "complement"
    if conflicts:
        wedge = "displace"
    elif missing:
        wedge = "fill_gap"

    return {
        "wedge": wedge,
        "conflicts": conflicts,
        "complements": complements,
        "missing": missing,
        "note": _wedge_note(wedge, conflicts, missing),
    }


def _maturity(by_cat: dict[str, list[str]]) -> str:
    n = len(by_cat)
    if n == 0:
        return "unknown"
    if n <= 1:
        return "thin"
    if n <= 3:
        return "emerging"
    if "crm" in by_cat and "analytics" in by_cat:
        return "mature"
    return "moderate"


def _wedge_note(wedge: str, conflicts: list[str], missing: list[str]) -> str:
    if wedge == "displace":
        return f"They're on {', '.join(conflicts)} — lead with a migration / cutover angle."
    if wedge == "fill_gap":
        return f"Stack gap in {', '.join(missing)} — sell the missing layer, not a rip-and-replace."
    if wedge == "complement":
        return "No direct conflict detected — position as complementary infrastructure."
    return ""


def _text(lead: dict[str, Any]) -> str:
    return " ".join(
        str(lead.get(k) or "")
        for k in ("ask_quote", "evidence", "what_they_do", "site_title", "context", "bio")
    )
